### PR TITLE
Fix compiler error of the cli example

### PR DESCRIPTION
**Pull request by skywhale**

### CODE REVIEW

**Comment by bschwind** [comment]
Thanks, @skywhale! This motivated me to fix the CI for this repo so further PRs can be better verified. Could you rebase this on `main` to pick up the CI checks?

**Comment by skywhale** [comment]
@bschwind thank you :) rebased!

**Comment by bschwind** [comment]
Oh! And I should update CI to use `--features="serde_support"` or else it wouldn't catch the very issue you're fixing. I'll add that next.

**Review by bschwind — APPROVED** [review]
LGTM!

**Pull request merged**
