### PR TITLE
Fix some clippy warnings

### PR DESCRIPTION
**Pull request by micwoj92**

### CODE REVIEW

**Comment by bschwind** [comment]
Hey nice! I don't have CI set up on this currently, but I'll test it locally for now :)

Just curious, are you using this project for anything in particular?

**Comment by micwoj92** [comment]
Not this, I found out about https://github.com/tonarino/innernet and I am just playing with it "for fun". I just saw this repo in the same organization and such clippy fixes are one of lowest hanging fruits possible (maybe besides spelling fixes)

**Review by bschwind — APPROVED** [review]
Well I couldn't quite get CI set up yet, but I cloned and ran this manually.

I think there might be a new clippy lint that snuck in between when you posted this and today, but I'll take care of that in another PR.

**Comment by micwoj92** [comment]
What do you mean you coudlnt get to set it up? It seems to work good in #12 and I think it should complete succesfully if you rebase on current master

**Comment by bschwind** [comment]
Ah, because it builds the `gui` example, it depends on `egui`, which needs some extra OS dependencies to work. I probably just need to copy what egui installs in its CI scripts to get it working.

**Comment by micwoj92** [comment]
it seems to only mis libxcb

**Pull request merged**
